name: Build and deploy

on:
  push:
    branches:
      - "*"
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure script permissions
        run: chmod +x ./dist.sh

      - name: Build dist
        run: |
          ./dist.sh
          echo "Listing files in the current directory:"
          ls -la

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/adguardcert-*.zip"  # 确保路径匹配
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          prerelease: ${{ contains(github.ref, '-') }}

      - name: Write PR URL
        if: github.event_name == 'pull_request'
        run: |
          echo "${{ github.event.pull_request.html_url }}" > pull_request_url.txt

      - name: Upload artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: adguardcert module build
          path: |
            adguardcert-*.zip
            README.md
            pull_request_url.txt

      - name: Update JSON
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git fetch origin
          ./update.sh
          git push origin master
          echo "Listing files in the current directory after update:"
          ls -la
